### ISSUE TITLE
New Sticker Icon Miscolored

### ISSUE THREAD

**Issue by macfeaster** [auscompgeek/fb-messenger-dark#13]
Still rocking this absolutely awesome style :smile: 
Facebook has changed the "sticker" icon, and this time apparently they made it all-black in their sprite sheet instead of gray. [Screenshot](https://gyazo.com/ee15aefd1daa0f04f79474a3c40f0efb)

I have temporarily fixed it with this line: 
```css
._30yy._4rv6._39bk { -webkit-filter: invert(100%); opacity: .55; }
```
