### ISSUE TITLE
Styling broken for replies

### ISSUE THREAD

**Issue by mogzol** [auscompgeek/fb-messenger-dark#28]
**Describe the bug**:
Messenger recently introduced message replies. The styling is a little broken for them.

**Steps to reproduce**:
1. View a message reply (particularly a reply that is only emojis, so not in a bubble)
2. It won't look good

**Screenshots**:
![image](https://user-images.githubusercontent.com/11789801/54860051-c2b49080-4cd1-11e9-9bf4-5247c632ac31.png)

**Additional context**:
I was able to make it look pretty good by adding the following styles:

```css
/* replies */
._4k7a {
  color: rgba(255, 255, 255, .5) !important;
}

._3058._s1-._6e6n {
  border-color: transparent !important;
  background-color: #2d2d30 !important;
}

._pyf {
  background-color: rgba(255, 255, 255, .3) !important;
}
```
